//
//  UIColor+PRJAdditions.h
//
//  Generated by Zeplin on 3/9/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (PRJAdditions)

+ (UIColor *)prj_pinkColor;

+ (UIColor *)prj_beigeColor;

@end
