//
//  UIColor+PRJAdditions.m
//
//  Generated by Zeplin on 3/9/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+PRJAdditions.h"

@implementation UIColor (PRJAdditions)

+ (UIColor *)prj_pinkColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:110.0f / 255.0f blue:110.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_beigeColor {
    return [UIColor colorWithRed:252.0f / 255.0f green:245.0f / 255.0f blue:236.0f / 255.0f alpha:1.0f];
}

@end
