//
//  UIFont+PRJAdditions.m
//
//  Generated by Zeplin on 3/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+PRJAdditions.h"

@implementation UIFont (PRJAdditions)

+ (UIFont *)prj_timeTextStyleFont {
	return [UIFont systemFontOfSize:32.0f weight:UIFontWeightLight];
}

+ (UIFont *)prj_missionTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Light" size:24.0f];
}

+ (UIFont *)prj_selectMessageTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Light" size:24.0f];
}

+ (UIFont *)prj_missionListTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Bold" size:16.0f];
}

+ (UIFont *)prj_tagGrayTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Medium" size:16.0f];
}

+ (UIFont *)prj_whiteTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Medium" size:16.0f];
}

+ (UIFont *)prj_selectDoneTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Medium" size:16.0f];
}

+ (UIFont *)prj_greyTextStyleFont {
	return [UIFont fontWithName:@"AppleSDGothicNeo-Medium" size:16.0f];
}

+ (UIFont *)prj_missionListCellTextStyleFont {
	return [UIFont systemFontOfSize:16.0f weight:UIFontWeightLight];
}

@end
