//
//  UIColor+PRJAdditions.m
//
//  Generated by Zeplin on 3/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+PRJAdditions.h"

@implementation UIColor (PRJAdditions)

+ (UIColor *)prj_pinkColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:110.0f / 255.0f blue:110.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_turquoiseBlueColor {
	return [UIColor colorWithRed:1.0f / 255.0f green:181.0f / 255.0f blue:188.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_veryLightPinkColor {
	return [UIColor colorWithRed:252.0f / 255.0f green:245.0f / 255.0f blue:236.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_greyishBrownColor {
	return [UIColor colorWithWhite:82.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_backGrayColor {
	return [UIColor colorWithWhite:216.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_warmGreyColor {
	return [UIColor colorWithWhite:155.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_peachyPinkColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:131.0f / 255.0f blue:131.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_greyishBrownTwoColor {
	return [UIColor colorWithWhite:74.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_veryLightPinkTwoColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:216.0f / 255.0f blue:214.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_salmonColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:112.0f / 255.0f blue:105.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)prj_pinkishGrey {
    return [UIColor colorWithRed:200.0f / 255.0f green:200.0f / 255.0f blue:200.0f / 255.0f alpha:1.0f];
}

@end
