//
//  UIColor+PRJAdditions.h
//
//  Generated by Zeplin on 3/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (PRJAdditions)

+ (UIColor *)prj_pinkColor;
+ (UIColor *)prj_turquoiseBlueColor;
+ (UIColor *)prj_veryLightPinkColor;
+ (UIColor *)prj_greyishBrownColor;
+ (UIColor *)prj_backGrayColor;
+ (UIColor *)prj_warmGreyColor;
+ (UIColor *)prj_peachyPinkColor;
+ (UIColor *)prj_greyishBrownTwoColor;
+ (UIColor *)prj_veryLightPinkTwoColor;
+ (UIColor *)prj_salmonColor;
+ (UIColor *)prj_pinkishGrey;

@end
