//
//  UIFont+PRJAdditions.h
//
//  Generated by Zeplin on 3/10/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (PRJAdditions)

+ (UIFont *)prj_timeTextStyleFont;
+ (UIFont *)prj_missionTextStyleFont;
+ (UIFont *)prj_selectMessageTextStyleFont;
+ (UIFont *)prj_missionListTextStyleFont;
+ (UIFont *)prj_tagGrayTextStyleFont;
+ (UIFont *)prj_whiteTextStyleFont;
+ (UIFont *)prj_selectDoneTextStyleFont;
+ (UIFont *)prj_greyTextStyleFont;
+ (UIFont *)prj_missionListCellTextStyleFont;

@end
